---
- hosts: 127.0.0.1
  sudo: yes
  vars:
    - ruby_version: 2.2.0
  tasks:
    - name: yum update
      yum: name=* state=latest
    - name: disable iptables
      service: name=iptables state=stopped enabled=no
    - name: install libselinux-python
      yum: name=libselinux-python state=latest
    - name: remove localtime
      file: path=/etc/localtime state=absent
    - name: make symlink to JST
      file: src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime state=link force=yes mode=0644
    - name: change locale
      command: sed -i "s/en_US/ja_JP/g" /etc/sysconfig/i18n
    - name: install remi repository
      command: rpm -Uvh --force http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
    - name: install apache
      yum: name=httpd state=latest
    - name: start apache and enabled
      service: name=httpd state=started enabled=yes
    - name: change owner
      file: dest=/var/www/html owner=vagrant recurse=yes
    - name: install php
      yum: name={{item}} enablerepo=remi,epel state=present
      with_items:
        - php
        - php-devel
        - php-mysql
        - php-mbstring
        - php-gd
      notify:
        - restart apache
    - name: copy php.ini.custom
      copy: src=php.ini.custom dest=/etc/php.ini backup=yes
      notify:
        - restart apache
    - name: install mysql
      yum: name=mysql-server enablerepo=remi,epel state=present
    - name: copy my.cnf.custom
      copy: src=my.cnf.custom dest=/etc/my.cnf backup=yes
    - name: start mysql and enabled
      service: name=mysqld state=started enabled=yes

    - name: install ruby dependencies
      yum: name={{item}} enablerepo=remi,epel state=present
      with_items:
        - gcc
        - openssl-devel
        - rpm-build
        - gcc-c++
        - bzip2
        - iconv-devel
        - libtool
        - zlib
        - zlib-devel
        - httpd-devel
        - openssl-devel
        - curl-devel
        - ncurses-devel
        - gdbm-devel
        - readline
        - readline-devel
        - sqlite-devel
        - libyaml-devel
        - libffi-devel
        - bison
    - name: git clone rbenv
      git: repo=https://github.com/sstephenson/rbenv.git dest=/home/vagrant/.rbenv
      sudo: no
    - name: update bash_profile
      copy: src=bash_profile.custom dest=/home/vagrant/.bash_profile backup=yes
      sudo: no 
    - name: reload shell
      shell: /bin/bash -l
      sudo: no
    - name: rbenv check
      shell: /bin/bash -lc "rbenv "
      sudo: no

    - name: git clone ruby-build
      git: repo=https://github.com/sstephenson/ruby-build.git dest=/home/vagrant/.rbenv/plugins/ruby-build
      sudo: no
    - name: install ruby
      shell: /bin/bash -lc "rbenv install {{ruby_version}} && rbenv global {{ruby_version}} && rbenv rehash"
      sudo: no

  handlers:
    - name: restart apache
      service: name=httpd state=restarted

