---
- hosts: 127.0.0.1
  sudo: yes
  vars:
    - ruby_version: 2.2.0
  tasks:
    - name: disable iptables
      service: name=iptables state=stopped enabled=no
    - name: install libselinux-python
      yum: name=libselinux-python state=latest
    - name: install remi repository
      command: rpm -Uvh --force http://rpms.famillecollet.com/enterprise/remi-release-6.rpm

    - name: install ruby dependencies
      yum: name={{item}} enablerepo=remi,epel state=present
      with_items:
        - gcc
        - openssl-devel
        - rpm-build
        - gcc-c++
        - bzip2
        - libtool
        - zlib
        - zlib-devel
        - httpd-devel
        - openssl-devel
        - curl-devel
        - ncurses-devel
        - gdbm-devel
        - readline
        - readline-devel
        - sqlite-devel
        - libyaml-devel
        - libffi-devel
        - bison
    - name: git clone rbenv
      git: repo=https://github.com/sstephenson/rbenv.git dest=/home/vagrant/.rbenv
      sudo: no
    - name: update bashrc
      copy: src=bashrc.custom dest=/home/vagrant/.bashrc backup=yes
      sudo: no 
    - name: reload shell
      shell: /bin/bash -l
      sudo: no
    - name: git clone ruby-build
      git: repo=https://github.com/sstephenson/ruby-build.git dest=/home/vagrant/.rbenv/plugins/ruby-build
      sudo: no
